// Generated by CoffeeScript 1.6.2
var validate, validateBody, validateQuery;

validate = require('./index').validate;

validateBody = function(schema) {
  return function(req, res, next) {
    var data, errors, _ref;

    _ref = validate(schema, req.body), errors = _ref.errors, data = _ref.data;
    if (!isEmpty(errors)) {
      return res.send(400, errors);
    } else {
      req.validBody = data;
      return next();
    }
  };
};

validateQuery = function(schema) {
  return function(req, res, next) {
    var data, errors, _ref;

    _ref = validate(schema, req.query, {
      weak: true
    }), errors = _ref.errors, data = _ref.data;
    if (!isEmpty(errors)) {
      return res.send(400, errors);
    } else {
      req.validQuery = data;
      return next();
    }
  };
};

validate = function(schema) {
  return function(req, res, next) {
    if (contains(['GET', 'HEAD', 'OPTIONS'], req.method)) {
      return validateQuery(schema)(req, res, next);
    } else {
      return validateBody(schema)(req, res, next);
    }
  };
};

module.exports = {
  validateBody: validateBody,
  validateQuery: validateQuery,
  validate: validate
};
